# 检测间隔
CheckDelay: 10
# 某个星级图鉴奖励
Stars:
  1s:
    - "nye give %player% 钻石 500"
  2s:
    - "nye give %player% 钻石 1000"
  3s:
    - "nye give %player% 钻石 2000"
  4s:
    - "nye give %player% 钻石 2000"
  5s:
    - "nye give %player% 钻石 2000"
  6s:
    - "nye give %player% 钻石 2500"
  7s:
    - "nye give %player% 钻石 3000"
  8s:
    - "nye give %player% 钻石 2000"
  9s:
    - "nye give %player% 钻石 800"
  10s:
    - "nye give %player% 钻石 3000"
# 星级图鉴奖励 Lore 中显示的内容
Info:
  1s:
    - " &f  - &a钻石 x500 "
  2s:
    - " &f  - &a钻石 x1000 "
  3s:
    - " &f  - &a钻石 x2000 "
  4s:
    - " &f  - &a钻石 x2000 "
  5s:
    - " &f  - &a钻石 x2000 "
  6s:
    - " &f  - &a钻石 x2500 "
  7s:
    - " &f  - &a钻石 x3000 "
  8s:
    - " &f  - &a钻石 x2000 "
  9s:
    - " &f  - &a钻石 x800 "
  10s:
    - " &f  - &a钻石 x3000 "