# 数据存储设置
save-option:
  # 可选: YAML, MYSQL 默认 YAML
  type: YAML
  # 数据库 URL 设定，例如: jdbc:mysql://127.0.0.1/minecraft, 格式：jdbc:mysql://MySQL地址/数据库名
  url: jdbc:mysql://localhost/minecraft
  # 数据库用户名
  user: "root"
  # 数据库密码
  password: "root"
  # 数据库读取超时打开数据锁时长, 2 = 1秒
  time-out: 20
  # 登录数据加载提示
  pull-message: true
# 时间格式
date-format: "yyyy-MM-dd HH:mm:ss"