name: PokePlate
main: com.aiyostudio.pokeplate.PokePlate
depend:
  - AyCore
  - PokeStar
softdepend:
  - PlaceholderAPI
version: @version@
api-version: 1.13
commands:
  pokeplate:
    aliases:
      - tj
      - plate
    description: Command for PokePlate.